### ISSUE TITLE
transaktionsid prüfen

### ISSUE THREAD

**Issue by fabianHAW** [Dutzel/TTV-Lab2#10]
prüfen der transaktionsid, ob die reihenfolge stimmt. prüfe ob die erhaltene ta id in NodeImpl.broadcast() fortlaufend ist. ist sie identisch mit der gespeicherten id, dann verwerfe den broadcast.

**Comment by Dutzel** [comment]
/**
		 * GIT Issue: #10
		 * Here we check, if a received transaction id was already forwarded.
		 * If a transaction id was allready forwarded, we discard the boradcast.
		 * Status: done
		 */
		if(!alreadyForwardedTransactionIDs.contains(info.getTransaction())){
			alreadyForwardedTransactionIDs.add(info.getTransaction());
			
			List<Node> sortedFingerTable = this.impl.getSortedFingerTable();
	
			// 2. case: broadcast comes from another node
			if(!this.getNodeID().equals(info.getSource())){
				// inform application
				if (this.notifyCallback != null) {
					if (this.logger.isEnabledFor(DEBUG)) {
						this.logger.debug("Inform my application about the broadcast from another node: " + info.toString());
					}
					this.notifyCallback.broadcast(info.getSource(), info.getTarget(), info.getHit());
				}
			}
			this.sendBroadcast(sortedFingerTable, 0, info);
		}else{
			if (this.logger.isEnabledFor(DEBUG)) {
				//System.err.println("Ignored transaction " + info.getTransaction() + ", because it was already forwarded.");
				//this.logger.debug("Ignored transaction " + info.getTransaction() + ", because it was already forwarded.");
			}
		}

**Comment by Dutzel** [comment]
Hierfür habe ich in der NodeImpl bei der Broadcast-Methode die Abfrage "if(!alreadyForwardedTransactionIDs.contains(info.getTransaction()))" hinzugefügt.

Nur wenn die Bedingung zutrifft, wird ein Broadcast weitergesendet. Außerdem wird nach der Bedingung die aktuelle TransaktionsID der Liste "alreadyForwardedTransactionIDs" hinzugefügt.

Außerdem habe ich versucht die Liste der alreadyForwardedTransactionIDs auf eine maximale Größe zu beschränken, sodass nur die X-Neuestes TransaktionsIDs in der Liste stehen. Dabei ist mir allerdings aufgefallen, dass wir uns nicht darauf verlassen können, weil teilweise noch relativ alte Transaktionen durch das "Netz" schwirren. Daher habe ich das erstmal rausgenommen, wir können das X natürlich höher ansetzen, nur ist dann die Frage inwieweit wir das brauchen.

Bei einer Sache bin ich mir unsicher:
Müssen wir bezüglich des asynchronen Verhaltens der Anwendung etwas beim Aufruf von alreadyForwardedTransactionIDs beachten?

**Comment by Dutzel** [comment]
Wenn du mit der Implementation so übereinstimmst, kannst du das Issue hier gerne einfach schließen.

**Comment by fabianHAW** [comment]
aus der aufgabe workpackage 2 geht hervor:

> Verwenden Sie eine einfach aufsteigende TransaktionsID, um den Gewinner eindeutig
identifizieren zu können. D.h. der Startknoten/spieler beginnt mit einer zufällig ge-
wählten TransaktionsID, welche für jede neue Nachricht erhöht wird.

d.h. wir dürfen keine eigene transaktionsID nutzen, sondern müssen die aus dem packet nehmen und immer um eins erhöhen. sind wir der erste, dann legen wir damit los..in der chordimpl nutzen wir bisher noch eine eigene und zählen die fleißig hoch. ich denke die taID muss in die nodeimpl wandern und von der chordimpl aus genutzt werden. wenn wir der startknoten sind, initialisieren wir sie. sonst zählen wir sie einfach hoch..

probleme mit dem asynchronen versand sehe ich derzeit nicht..

**Comment by fabianHAW** [comment]
die id ist nun in die nodeimpl gewandert. bekommen wir einen broadcast eines anderen knoten und die id ist noch nicht in unserer liste wird diese entsprechend gesetzt. schicken wir einen broadcast aus der chordimpl los, zählen wir die id einfach um einen hoch..
