### ISSUE TITLE
testgrundlage erstellen

### ISSUE THREAD

**Issue by fabianHAW** [Dutzel/TTV-Lab2#2]
erstellen einer grundlage mit der wir testen können: z.b. 4 knoten lokal erzeugen die das spiel spielen. ein knoten ist durch "localhost:<port>" definiert.

**Comment by fabianHAW** [comment]
erstellen einer einfachen strategie die die knoten beschießt.

**Comment by Dutzel** [comment]
Die Testgrundlage ist in der Klasse LocalTestingMain implementiert. Diese solltest du einfach 
starten können. 

Geht natürlich schicker, doch für den Anfang denke ist sollte es reichen :)

**Comment by Dutzel** [comment]
Schiffe werden platziert und es kann ein Ziel ausgesucht und drauf geschossen werden. Somit sollte die Testgrundlage stehen. Als nächstes sollten wir prüfen, ob bei dem Broadcast alles richtig läuft und weitere Spiellogik implementieren.
