### ISSUE TITLE
targetauswahl

### ISSUE THREAD

**Issue by fabianHAW** [Dutzel/TTV-Lab2#7]
einfache implementierung ein target zu wählen

**Comment by Dutzel** [comment]
Wie im Readme vorgegeben in der StrategyOne implementiert (leichte Abweichungen zur Vereinfachung)

**Comment by fabianHAW** [comment]
chooseRandomTarget() (wenn die jeweiligen listen für hits und nohits noch leer sind) läuft noch nicht ganz, da die while bedingung beim generieren von random werten noch einen haken hat.

**Comment by fabianHAW** [comment]
auch hier wie in #16 wird der sonderfall mit dem ersten knoten behandelt.
